travis:
  secure:
    BINSTAR_TOKEN: Y1ouwoEmrfvhd/ukJgQueB4HYpGg4oUlXhyNdOoUOjFYqNSbXnzv9hNMBlKE07PAiVUvG8mmbvAMayWPYa74OwuWMBzONbuC/v6ufNubHYawK/By2FaL+Xs/U8Os7BQN7S4EaqqjwL7QfhAXIwRFtTDOpdG2eh6nwEeoGesdcwkl80/9G2mcsdL2fc9wy1cAYaJAWVP+WKCRDfXng4QhrwY5zME9MfqFc824pOpROopvnTJA4SviJwmlGuHMHHEO7m0/jjqLHKNJXGEi1F7FUFgoHhmW/KeOJMpFeB+5j7f42sdPjE9gX4UFtp5PjsxBbGdi65Qqh3VJnbB3OMtGNkjJw5L0+5YtvCrK9ogQS/rfJKPeRW8xIwO7+0m4EO6o7rmzQFKEunS5eH767BO2vLnjBCOfZhsj6GHkHdDXWc9shb3NTGWnOdRXIR6vf2wITK0mcTqwZHRmSqX3pZwVMx3Hh/XXMEVq0F1W+n8oZ08lWtwWB8u/YQgV4FNGmc/VSrM8brM+4+slmtZFDvtog0ftJq/91cgpZAykz2JNewKEof6j5sgyI6lz9dnxli9Utzx6UIhZ2LxUCcqFg5iT6ADtT+6rhOOcORpTAKiyA1XvFBrHwYXluaRJi0YxsCxcb6/Rpv4HIiN92Zkpbr/T8GhWozFTzLvU5bV7X4nR5rg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
